server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # ---------- En-têtes de sécurité ----------
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=(self)" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https:; connect-src 'self'; frame-src 'self' https:; form-action 'self' https:; base-uri 'self'; object-src 'none'; frame-ancestors 'none'" always;

    # ---------- Compression ----------
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml application/manifest+json;

    location = /healthz { return 200 'ok'; add_header Content-Type text/plain; }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
